name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install lcov avr-libc binutils-avr gcc-avr
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build rtu_atmega328p
      run: make -f rtu_atmega328p.mk
    - name: build rtu_linux
      run: make -f rtu_linux.mk
    - name: build tty_linux_tests
      run: make -f tty_linux_tests.mk
    - name: run tty_linux_tests
      run: make -f tty_linux_tests.mk run
    - name: build rtu_linux_tests
      run: make -f rtu_linux_tests.mk 
    - name: run rtu_linux_tests
      run: make -f rtu_linux_tests.mk run
  asan_build:
    runs-on: ubuntu-24.04
    env:
      DEBUG: 1
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build and run tty_linux_tests
      run: make -f tty_linux_tests.mk run
    - name: build and run rtu_linux_tests
      run: make -f rtu_linux_tests.mk run
