name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Install deps
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: make -f rtu_linux.mk
