name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build_rtu_linux
      run: make -f rtu_linux.mk
    - name: build_tty_linux_tests
      run: make -f tty_linux_tests.mk
    - name: run_tty_linux_tests
      run: make -f tty_linux_tests.mk run
    - name: build_rtu_linux_tests
      run: make -f rtu_linux_tests.mk 
    - name: run_rtu_linux_tests
      run: make -f rtu_linux_tests.mk run
